### ISSUE TITLE
How to skip scanning JARs for TLD

### ISSUE THREAD

**Issue by ayamshchikov** [joinfaces/joinfaces#283]
I'm facing unexplained slow startup time of the JoinFaces-based application packaged as WAR. 
This is happening only on select computers (on some, app starts in 13 sec, on others in 1500 sec.) and only for Spring Boot apps. Similar apps starts under JBoss or Liberty app servers just fine everywhere.
Still could not figure out if this is  security settings, network, firewall or anti-virus tools.

It seems like application spends a lot of time on scanning JAR for TLD files - I have a lot of messages like this:
```
org.apache.jasper.servlet.TldScanner : No TLD files were found in [jar:file:/C:/Development/workspace-Cloud/PrimeFacesDemoSBwar/target/primefacesdemoSB.war!/WEB-INF/lib/primefaces-5.3.jar]. Consider adding the JAR to the tomcat.util.scan.StandardJarScanFilter.jarsToSkip property in CATALINA_BASE/conf/catalina.properties file.
```
My question is, what is location of that catalina.properties file in Spring Boot app, packaged as WAR?

**Comment by persapiens** [comment]
Hi @ayamshchikov 

Maybe you could configure tomcat programmatically with TomcatContextCustomizer like [here.](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-use-tomcat-legacycookieprocessor).

Other configurations are done at [application.yml](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)

**Comment by ayamshchikov** [comment]
Thanks, @persapiens 
I've already tried to add these properties as per documentation, but TLD still scanned (I could not find properties for JarScan in the Spring Boot docs).
Here is what I have in my application.yml
```
server:
    tomcat:
      additional-tld-skip-patterns: "*.jar"
      context:
        JarScanner:
          scanClassPath: false
          JarScanFilter:
            defaultPluggabilityScan: "false"
      util:
        scan:
          StandardJarScanFilter:
            jarsToSkip: "*"
```
