### ISSUE TITLE
joinfaces.jsf.config-files not working when running as JAR

### ISSUE THREAD

**Issue by OskarsPakers** [joinfaces/joinfaces#846]
I am trying to achieve to load different faces-config.xml files depending on the activated profile. The goal is to have different supported locales in JSF application depending on Spring profile without packaging two different jar archives.

I have created files 
src/main/resources/META-INF/resources/faces-config-lt.xml 
src/main/resources/META-INF/resources/faces-config-lv.xml
and I would like to load the correct file based on profile "lv" or "lt" correspondingly with application.yml
```
joinfaces:
  jsf:
    project-stage: development
---

spring:
  profiles: lv
joinfaces:
  jsf:
    config-files: faces-config-lv.xml

---

spring:
  profiles: lt
joinfaces:
  jsf:
    config-files: faces-config-lt.xml

```

This works correctly if I run application with `mvn spring-boot:run` but it doesn't when I run packaged .jar file with `java -jar`.
It logs warning on startup that faces-config-lt.xml cannot be loaded.
```
JSF1067: Resource faces-config-lt.xml specified by the javax.faces.CONFIG_FILES configuration option cannot be found.  The resource will be ignored.
```

Using:
Spring boot: 2.3.7.RELEASE
Joinfaces: 4.3.6

I have created a demo application to demonstrate the issue https://github.com/OskarsPakers/joinfaces-conditional-faces-config
