### ISSUE TITLE
Gradle: Dependabot Automatically Generate PR's

### ISSUE THREAD

**Issue by melloware** [joinfaces/joinfaces#888]
If you add `dependabot.yml` to the root of your `.github` directory it will generate automatic PR's when new versions of libraries come out.

See my example here for PrimeFaces Extensions: https://github.com/primefaces-extensions/primefaces-extensions/tree/master/.github

Just add this `dependabot.yml` for Gradle.
```yaml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
